package datadome

type JsonFile struct {
	Events        []interface{} `json:"events"`
	EventCounters struct {
		Mousemove  int `json:"mousemove"`
		Click      int `json:"click"`
		Scroll     int `json:"scroll"`
		Touchstart int `json:"touchstart"`
		Touchend   int `json:"touchend"`
		Touchmove  int `json:"touchmove"`
		Keydown    int `json:"keydown"`
		Keyup      int `json:"keyup"`
	} `json:"eventCounters"`
	JsType       string `json:"jsType"`
	Cid          string `json:"cid"`
	Ddk          string `json:"ddk"`
	Referer      string `json:"Referer"`
	Request      string `json:"request"`
	ResponsePage string `json:"responsePage"`
	Ddv          string `json:"ddv"`
	JsData       struct {
		Ttst      float64 `json:"ttst"`
		Ifov      bool    `json:"ifov"`
		Tagpu     float64 `json:"tagpu"`
		Glvd      string  `json:"glvd"`
		Glrd      string  `json:"glrd"`
		Hc        int     `json:"hc"`
		BrOh      int     `json:"br_oh"`
		BrOw      int     `json:"br_ow"`
		Ua        string  `json:"ua"`
		Wbd       bool    `json:"wbd"`
		Wdif      bool    `json:"wdif"`
		Wdifrm    bool    `json:"wdifrm"`
		Npmtm     bool    `json:"npmtm"`
		BrH       int     `json:"br_h"`
		BrW       int     `json:"br_w"`
		Nddc      int     `json:"nddc"`
		RsH       int     `json:"rs_h"`
		RsW       int     `json:"rs_w"`
		RsCd      int     `json:"rs_cd"`
		Phe       bool    `json:"phe"`
		Nm        bool    `json:"nm"`
		Jsf       bool    `json:"jsf"`
		Lg        string  `json:"lg"`
		Pr        float64 `json:"pr"`
		ArsH      int     `json:"ars_h"`
		ArsW      int     `json:"ars_w"`
		Tz        int     `json:"tz"`
		StrSs     bool    `json:"str_ss"`
		StrLs     bool    `json:"str_ls"`
		StrIdb    bool    `json:"str_idb"`
		StrOdb    bool    `json:"str_odb"`
		Plgod     bool    `json:"plgod"`
		Plg       int     `json:"plg"`
		Plgne     bool    `json:"plgne"`
		Plgre     bool    `json:"plgre"`
		Plgof     bool    `json:"plgof"`
		Plggt     bool    `json:"plggt"`
		Pltod     bool    `json:"pltod"`
		Hcovdr    bool    `json:"hcovdr"`
		Hcovdr2   bool    `json:"hcovdr2"`
		Plovdr    bool    `json:"plovdr"`
		Plovdr2   bool    `json:"plovdr2"`
		Ftsovdr   bool    `json:"ftsovdr"`
		Ftsovdr2  bool    `json:"ftsovdr2"`
		Lb        bool    `json:"lb"`
		Eva       int     `json:"eva"`
		Lo        bool    `json:"lo"`
		TsMtp     int     `json:"ts_mtp"`
		TsTec     bool    `json:"ts_tec"`
		TsTsa     bool    `json:"ts_tsa"`
		Vnd       string  `json:"vnd"`
		Bid       string  `json:"bid"`
		Mmt       string  `json:"mmt"`
		Plu       string  `json:"plu"`
		Hdn       bool    `json:"hdn"`
		Awe       bool    `json:"awe"`
		Geb       bool    `json:"geb"`
		Dat       bool    `json:"dat"`
		Med       string  `json:"med"`
		Aco       string  `json:"aco"`
		Acots     bool    `json:"acots"`
		Acmp      string  `json:"acmp"`
		Acmpts    bool    `json:"acmpts"`
		Acw       string  `json:"acw"`
		Acwts     bool    `json:"acwts"`
		Acma      string  `json:"acma"`
		Acmats    bool    `json:"acmats"`
		Acaa      string  `json:"acaa"`
		Acaats    bool    `json:"acaats"`
		Ac3       string  `json:"ac3"`
		Ac3Ts     bool    `json:"ac3ts"`
		Acf       string  `json:"acf"`
		Acfts     bool    `json:"acfts"`
		Acmp4     string  `json:"acmp4"`
		Acmp4Ts   bool    `json:"acmp4ts"`
		Acmp3     string  `json:"acmp3"`
		Acmp3Ts   bool    `json:"acmp3ts"`
		Acwm      string  `json:"acwm"`
		Acwmts    bool    `json:"acwmts"`
		Ocpt      bool    `json:"ocpt"`
		Vco       string  `json:"vco"`
		Vcots     bool    `json:"vcots"`
		Vch       string  `json:"vch"`
		Vchts     bool    `json:"vchts"`
		Vcw       string  `json:"vcw"`
		Vcwts     bool    `json:"vcwts"`
		Vc3       string  `json:"vc3"`
		Vc3Ts     bool    `json:"vc3ts"`
		Vcmp      string  `json:"vcmp"`
		Vcmpts    bool    `json:"vcmpts"`
		Vcq       string  `json:"vcq"`
		Vcqts     bool    `json:"vcqts"`
		Vc1       string  `json:"vc1"`
		Vc1Ts     bool    `json:"vc1ts"`
		Dvm       int     `json:"dvm"`
		Sqt       bool    `json:"sqt"`
		So        string  `json:"so"`
		Wdw       bool    `json:"wdw"`
		Cokys     string  `json:"cokys"`
		Ecpc      bool    `json:"ecpc"`
		Lgs       bool    `json:"lgs"`
		Lgsod     bool    `json:"lgsod"`
		Psn       bool    `json:"psn"`
		Edp       bool    `json:"edp"`
		Addt      bool    `json:"addt"`
		Wsdc      bool    `json:"wsdc"`
		Ccsr      bool    `json:"ccsr"`
		Nuad      bool    `json:"nuad"`
		Bcda      bool    `json:"bcda"`
		Idn       bool    `json:"idn"`
		Capi      bool    `json:"capi"`
		Svde      bool    `json:"svde"`
		Vpbq      bool    `json:"vpbq"`
		Ucdv      bool    `json:"ucdv"`
		Spwn      bool    `json:"spwn"`
		Emt       bool    `json:"emt"`
		Bfr       bool    `json:"bfr"`
		Dbov      bool    `json:"dbov"`
		Prm       bool    `json:"prm"`
		Tzp       string  `json:"tzp"`
		Cvs       bool    `json:"cvs"`
		Usb       string  `json:"usb"`
		Jset      int     `json:"jset"`
		Cfpfe     string  `json:"cfpfe"`
		Stcfp     string  `json:"stcfp"`
		Dcok      string  `json:"dcok"`
		MpCx      int     `json:"mp_cx"`
		MpCy      int     `json:"mp_cy"`
		MpTr      bool    `json:"mp_tr"`
		MpMx      int     `json:"mp_mx"`
		MpMy      int     `json:"mp_my"`
		MpSx      int     `json:"mp_sx"`
		MpSy      int     `json:"mp_sy"`
		MmMd      int     `json:"mm_md"`
		Tbce      int     `json:"tbce"`
		EsSigmdn  float64 `json:"es_sigmdn"`
		EsMumdn   float64 `json:"es_mumdn"`
		EsDistmdn float64 `json:"es_distmdn"`
		EsAngsmdn float64 `json:"es_angsmdn"`
		EsAngemdn float64 `json:"es_angemdn"`
	} `json:"jsData"`
}
